FROM node:18.16-slim

WORKDIR /home/app

COPY back.js .

RUN npm init -y

EXPOSE 4000

CMD ["node", "back.js"]

# docker build -t back-app -f Dockerfile-Back .
# docker run --name back --network rede_webacademy -p 4000:4000 back-app