FROM node:18.16-slim

WORKDIR /home/app

COPY front.js .

RUN npm init -y

RUN npm install querystring

EXPOSE 3000

CMD ["node", "front.js"]

# docker build -t front-app -f Dockerfile-Front .
# docker run -d --name front --network rede_webacademy -p 3000:3000 front-app