version: '3'

services:
  mysql_container:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: webt52025
      MYSQL_DATABASE: webacademy
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bd/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - rede_webacademy

  phpmyadmin_container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - mysql_container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: webt52025
    networks:
      - rede_webacademy

  backend_container:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend_container
    environment:
        DATABASE_URL: mysql://root:webt52025@mysql_container:3306/webacademy
    ports:
      - "4444:4444"
    depends_on:
      - mysql_container
    networks:
      - rede_webacademy

  front_container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front_container
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend_container
    networks:
      - rede_webacademy

volumes:
  mysql_data:

networks:
  rede_webacademy:
    driver: bridge