version: '3'

services:
  mysql: 
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webacademy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # docker exec -i mysql_container mysql -u root -proot webacademy < ./bd/script.sql
      - ./bd/script.sql:/docker-entrypoint-initdb.d/script.sql
      # docker exec -i mysql_container mysql -u root -proot webacademy < ./bd/dados-livros.sql
      - ./bd/dados-livros.sql:/docker-entrypoint-initdb.d/dados-livros.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "4444:4444"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/.env:/app/.env

volumes:
  mysql_data:
